.TH ZERGMAP 1
.SH NAME
zergmap - read psychic captures from any number of files process zergs to determine if 2 or more disjoint route are available to cause a resonance cascade. 
.SH SYNOPSIS
.B zergmap
[\fR \fI-h\fR]
[\fR \fI##\fR]
[\fR \fIPCAP FILENAME\fR]
[\fR\fI...\fR]
.SH DESCRIPTION
.B intersect 
read psychic captures from any number of files process zergs to determine if 2 or more disjoint route are available to cause a resonance cascade.

